version: '3.3'
services:
    radarr:
        container_name: radarr
        ports:
            - '7878:7878'
        environment:
            - PUID=1033
            - PGID=65540
            - TZ=Europe/Berlin
            - UMASK_SET=022
        volumes:
            - '/volume1/docker/radarr:/config'
            - '/volume1/eggface:/data'
        restart: always
        image: ghcr.io/linuxserver/radarr:5.2.6

    sonarr:
      image: ghcr.io/linuxserver/sonarr:3.0.10
      container_name: sonarr
      environment:
        - PUID=1033
        - PGID=65540
        - TZ=Europe/Berlin
      volumes:
        - '/volume1/docker/sonarr:/config'
        - '/volume1/eggface:/data'
      ports:
        - 8989:8989

    sabnzbd:
      image: ghcr.io/linuxserver/sabnzbd:4.1.0
      container_name: sabnzbd
      environment:
        - PUID=1033
        - PGID=65540
        - TZ=Europe/Berlin
      volumes:
        - '/volume1/docker/sabnzbd:/config'
        - '/volume1/eggface:/data'
      ports:
        - 8080:8080
        - 9090:9090

    plextraktsync:
      image: ghcr.io/taxel/plextraktsync:0.27.13
      command: sync
      container_name: plextraktsync
      restart: on-failure:2
      volumes:
        - /volume1/docker/plextraktsync:/app/config
      environment:
        - PUID=1033
        - PGID=65540
        - TZ=Europe/Berlin  
